name: flutter_attendace
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  calendar_timeline_sbk: ^1.1.7
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  http: ^1.2.2
  image: ^4.1.7
  image_picker: ^1.1.1
  intl: ^0.18.1
  location: ^7.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  tflite_flutter: ^0.10.4
  
  
dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
